import type { LanguageCode } from '../types';

export const uiText: Record<LanguageCode, Record<string, string>> = {
  it: {
    chooseVenue: 'Scegli il locale',
    menu: 'Menu',
    search: 'Cerca piatti, ingredienti, allergeni',
    all: 'Tutto',
    featured: 'In evidenza',
    allergens: 'Allergeni',
    noResults: 'Nessun piatto trovato.',
    changeVenue: 'Cambia locale',
    admin: 'Admin',
    adminArea: 'Area admin',
    chooseAdminVenue: 'Scegli il locale da gestire',
    manageMenu: 'Gestisci menu',
    adminSeparateLink: 'Questo spazio è separato dal menu clienti. Accesso protetto con PIN demo 2222.',
    pin: 'PIN amministratore',
    enterPin: 'Inserisci PIN demo',
    unlock: 'Entra',
    wrongPin: 'PIN non corretto.',
    close: 'Chiudi',
    active: 'Attivo',
    inactive: 'Disattivo',
    price: 'Prezzo',
    category: 'Categoria',
    save: 'Salva',
    addDish: 'Nuovo piatto',
    addCategory: 'Nuova categoria',
    dishes: 'Piatti',
    categories: 'Categorie',
    qrLinks: 'QR e link',
    photo: 'Foto',
    description: 'Descrizione',
    name: 'Nome',
    supabaseLocal: 'Dati locali demo attivi. Supabase non configurato.',
    supabaseReady: 'Supabase configurato: uso snapshot remoto se disponibile.',
    openMenu: 'Apri menu'
  },
  en: {
    chooseVenue: 'Choose venue',
    menu: 'Menu',
    search: 'Search dishes, ingredients, allergens',
    all: 'All',
    featured: 'Featured',
    allergens: 'Allergens',
    noResults: 'No dishes found.',
    changeVenue: 'Change venue',
    admin: 'Admin',
    adminArea: 'Admin area',
    chooseAdminVenue: 'Choose the venue to manage',
    manageMenu: 'Manage menu',
    adminSeparateLink: 'This area is separate from the customer menu. Protected with demo PIN 2222.',
    pin: 'Admin PIN',
    enterPin: 'Enter demo PIN',
    unlock: 'Unlock',
    wrongPin: 'Wrong PIN.',
    close: 'Close',
    active: 'Active',
    inactive: 'Inactive',
    price: 'Price',
    category: 'Category',
    save: 'Save',
    addDish: 'New dish',
    addCategory: 'New category',
    dishes: 'Dishes',
    categories: 'Categories',
    qrLinks: 'QR and links',
    photo: 'Photo',
    description: 'Description',
    name: 'Name',
    supabaseLocal: 'Local demo data active. Supabase is not configured.',
    supabaseReady: 'Supabase configured: using remote snapshot when available.',
    openMenu: 'Open menu'
  },
  fr: {
    chooseVenue: 'Choisir le lieu',
    menu: 'Menu',
    search: 'Chercher plats, ingrédients, allergènes',
    all: 'Tout',
    featured: 'À découvrir',
    allergens: 'Allergènes',
    noResults: 'Aucun plat trouvé.',
    changeVenue: 'Changer de lieu',
    admin: 'Admin',
    adminArea: 'Espace admin',
    chooseAdminVenue: 'Choisir le lieu à gérer',
    manageMenu: 'Gérer le menu',
    adminSeparateLink: 'Cet espace est séparé du menu client. Accès protégé par le PIN démo 2222.',
    pin: 'PIN administrateur',
    enterPin: 'Saisir le PIN démo',
    unlock: 'Entrer',
    wrongPin: 'PIN incorrect.',
    close: 'Fermer',
    active: 'Actif',
    inactive: 'Inactif',
    price: 'Prix',
    category: 'Catégorie',
    save: 'Enregistrer',
    addDish: 'Nouveau plat',
    addCategory: 'Nouvelle catégorie',
    dishes: 'Plats',
    categories: 'Catégories',
    qrLinks: 'QR et liens',
    photo: 'Photo',
    description: 'Description',
    name: 'Nom',
    supabaseLocal: 'Données locales de démo actives. Supabase non configuré.',
    supabaseReady: 'Supabase configuré : snapshot distant si disponible.',
    openMenu: 'Ouvrir le menu'
  },
  de: {
    chooseVenue: 'Lokal wählen',
    menu: 'Speisekarte',
    search: 'Gerichte, Zutaten, Allergene suchen',
    all: 'Alles',
    featured: 'Empfohlen',
    allergens: 'Allergene',
    noResults: 'Keine Gerichte gefunden.',
    changeVenue: 'Lokal wechseln',
    admin: 'Admin',
    adminArea: 'Admin-Bereich',
    chooseAdminVenue: 'Lokal zur Verwaltung wählen',
    manageMenu: 'Menü verwalten',
    adminSeparateLink: 'Dieser Bereich ist vom Gästemenü getrennt. Geschützt mit Demo-PIN 2222.',
    pin: 'Admin-PIN',
    enterPin: 'Demo-PIN eingeben',
    unlock: 'Öffnen',
    wrongPin: 'Falsche PIN.',
    close: 'Schließen',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    price: 'Preis',
    category: 'Kategorie',
    save: 'Speichern',
    addDish: 'Neues Gericht',
    addCategory: 'Neue Kategorie',
    dishes: 'Gerichte',
    categories: 'Kategorien',
    qrLinks: 'QR und Links',
    photo: 'Foto',
    description: 'Beschreibung',
    name: 'Name',
    supabaseLocal: 'Lokale Demodaten aktiv. Supabase ist nicht konfiguriert.',
    supabaseReady: 'Supabase konfiguriert: Remote-Snapshot, wenn verfügbar.',
    openMenu: 'Menü öffnen'
  },
  es: {
    chooseVenue: 'Elige local',
    menu: 'Menú',
    search: 'Buscar platos, ingredientes, alérgenos',
    all: 'Todo',
    featured: 'Destacados',
    allergens: 'Alérgenos',
    noResults: 'No se encontraron platos.',
    changeVenue: 'Cambiar local',
    admin: 'Admin',
    adminArea: 'Área admin',
    chooseAdminVenue: 'Elige el local a gestionar',
    manageMenu: 'Gestionar menú',
    adminSeparateLink: 'Esta área está separada del menú de clientes. Protegida con PIN demo 2222.',
    pin: 'PIN administrador',
    enterPin: 'Introduce PIN demo',
    unlock: 'Entrar',
    wrongPin: 'PIN incorrecto.',
    close: 'Cerrar',
    active: 'Activo',
    inactive: 'Inactivo',
    price: 'Precio',
    category: 'Categoría',
    save: 'Guardar',
    addDish: 'Nuevo plato',
    addCategory: 'Nueva categoría',
    dishes: 'Platos',
    categories: 'Categorías',
    qrLinks: 'QR y enlaces',
    photo: 'Foto',
    description: 'Descripción',
    name: 'Nombre',
    supabaseLocal: 'Datos demo locales activos. Supabase no configurado.',
    supabaseReady: 'Supabase configurado: snapshot remoto si está disponible.',
    openMenu: 'Abrir menú'
  }
};

export const allergenLabels: Record<string, Record<LanguageCode, string>> = {
  gluten: { it: 'Glutine', en: 'Gluten', fr: 'Gluten', de: 'Gluten', es: 'Gluten' },
  milk: { it: 'Latte', en: 'Milk', fr: 'Lait', de: 'Milch', es: 'Leche' },
  eggs: { it: 'Uova', en: 'Eggs', fr: 'Oeufs', de: 'Eier', es: 'Huevos' },
  nuts: { it: 'Frutta a guscio', en: 'Tree nuts', fr: 'Fruits à coque', de: 'Schalenfrüchte', es: 'Frutos secos' },
  celery: { it: 'Sedano', en: 'Celery', fr: 'Céleri', de: 'Sellerie', es: 'Apio' },
  sulfites: { it: 'Solfiti', en: 'Sulfites', fr: 'Sulfites', de: 'Sulfite', es: 'Sulfitos' },
  molluscs: { it: 'Molluschi', en: 'Molluscs', fr: 'Mollusques', de: 'Weichtiere', es: 'Moluscos' },
  fish: { it: 'Pesce', en: 'Fish', fr: 'Poisson', de: 'Fisch', es: 'Pescado' },
  sesame: { it: 'Sesamo', en: 'Sesame', fr: 'Sésame', de: 'Sesam', es: 'Sésamo' },
  soy: { it: 'Soia', en: 'Soy', fr: 'Soja', de: 'Soja', es: 'Soja' }
};

export const txt = (lang: LanguageCode, key: string) => uiText[lang][key] ?? uiText.it[key] ?? key;

export const allergenText = (allergen: string, lang: LanguageCode) =>
  allergenLabels[allergen]?.[lang] ?? allergen;
