import type { LanguageCode } from '../types';

export const uiText: Record<LanguageCode, Record<string, string>> = {
  it: {
    chooseExperience: 'Scegli la tua esperienza',
    chooseExperienceLine1: 'Scegli',
    chooseExperienceLine2: 'La tua',
    chooseExperienceLine3: 'Esperienza',
    diningEyebrow: 'Per cenare',
    diningTitle: 'Ristorante',
    diningDescription: "Un percorso tra sapori autentici, materie prime d'eccellenza e dettagli che fanno la differenza.",
    aperitivoEyebrow: 'Per aperitivo',
    aperitivoTitle: 'Aperitivo',
    aperitivoDescription: 'Il momento perfetto per rilassarsi tra cocktail artigianali, bollicine selezionate e piccoli assaggi gourmet.',
    chooseVenue: 'Scegli il locale',
    menu: 'Menu',
    search: 'Cerca piatti, ingredienti, allergeni',
    all: 'Tutto',
    featured: 'In evidenza',
    allergens: 'Allergeni',
    noResults: 'Nessun piatto trovato.',
    changeVenue: 'Cambia locale',
    admin: 'Admin',
    adminArea: 'Area admin',
    chooseAdminVenue: 'Scegli la categoria da gestire',
    manageMenu: 'Gestisci menu',
    manageMenuCucina: 'Gestisci menu cucina',
    manageMenuAperitivi: 'Gestisci menu aperitivi',
    adminSeparateLink: 'Questo spazio è separato dal menu clienti. Accesso protetto con email e password.',
    pin: 'PIN amministratore',
    enterPin: 'Inserisci PIN demo',
    unlock: 'Entra',
    wrongPin: 'PIN non corretto.',
    close: 'Chiudi',
    active: 'Attivo',
    inactive: 'Disattivo',
    price: 'Prezzo',
    category: 'Categoria',
    save: 'Salva',
    addDish: 'Nuovo piatto',
    addCategory: 'Nuova categoria',
    dishes: 'Piatti',
    categories: 'Categorie',
    qrLinks: 'QR e link',
    photo: 'Foto',
    description: 'Descrizione',
    name: 'Nome',
    supabaseLocal: 'Dati locali demo attivi. Supabase non configurato.',
    supabaseReady: 'Supabase attivo. I dati vengono salvati online.',
    openMenu: 'Apri menu',
    email: 'Email',
    password: 'Password',
    loginTitle: 'Accesso admin',
    logout: 'Disconnetti',
    serviceSelectTitle: 'Scegli il servizio',
    serviceCucina: 'Ristorante / Cucina',
    serviceAperitivo: 'Aperitivo',
    aperitivoComingSoon: 'La sezione aperitivo è in aggiornamento. Torna presto.',
    serviceTypeLabel: 'Tipo di servizio'
  },
  en: {
    chooseExperience: 'Choose your experience',
    chooseExperienceLine1: 'Choose',
    chooseExperienceLine2: 'Your',
    chooseExperienceLine3: 'Experience',
    diningEyebrow: 'For dinner',
    diningTitle: 'Cuisine',
    diningDescription: 'Contemporary Italian flavors, selected wines, and a welcome that invites you to linger.',
    aperitivoEyebrow: 'For aperitivo',
    aperitivoTitle: 'Cocktail Bar',
    aperitivoDescription: 'Elegant mixology, refined small bites, and a vibrant mood created for the aperitivo ritual.',
    chooseVenue: 'Choose venue',
    menu: 'Menu',
    search: 'Search dishes, ingredients, allergens',
    all: 'All',
    featured: 'Featured',
    allergens: 'Allergens',
    noResults: 'No dishes found.',
    changeVenue: 'Change venue',
    admin: 'Admin',
    adminArea: 'Admin area',
    chooseAdminVenue: 'Choose the venue to manage',
    manageMenu: 'Manage menu',
    manageMenuCucina: 'Manage dining menu',
    manageMenuAperitivi: 'Manage aperitivo menu',
    adminSeparateLink: 'This area is separate from the customer menu. Access is protected with email and password.',
    pin: 'Admin PIN',
    enterPin: 'Enter admin PIN',
    unlock: 'Unlock',
    wrongPin: 'Wrong PIN.',
    close: 'Close',
    active: 'Active',
    inactive: 'Inactive',
    price: 'Price',
    category: 'Category',
    save: 'Save',
    addDish: 'New dish',
    addCategory: 'New category',
    dishes: 'Dishes',
    categories: 'Categories',
    qrLinks: 'QR and links',
    photo: 'Photo',
    description: 'Description',
    name: 'Name',
    supabaseLocal: 'Local demo data active. Supabase is not configured.',
    supabaseReady: 'Supabase active. Data is saved online.',
    openMenu: 'Open menu',
    email: 'Email',
    password: 'Password',
    loginTitle: 'Admin login',
    logout: 'Sign out',
    serviceSelectTitle: 'Choose a service',
    serviceCucina: 'Restaurant / Kitchen',
    serviceAperitivo: 'Aperitivo',
    aperitivoComingSoon: 'The aperitivo section is being updated. Come back soon.',
    serviceTypeLabel: 'Service type'
  },
  fr: {
    chooseExperience: 'Choisissez votre experience',
    chooseExperienceLine1: 'Choisissez',
    chooseExperienceLine2: 'Votre',
    chooseExperienceLine3: 'Expérience',
    diningEyebrow: 'Pour dîner',
    diningTitle: 'Cuisine',
    diningDescription: 'Saveurs italiennes contemporaines, vins choisis et un accueil qui donne envie de rester.',
    aperitivoEyebrow: "Pour l'apéritif",
    aperitivoTitle: 'Bar à cocktails',
    aperitivoDescription: "Mixologie élégante, petites bouchées raffinées et une atmosphère vivante pensée pour l'apéritif.",
    chooseVenue: 'Choisir le lieu',
    menu: 'Menu',
    search: 'Chercher plats, ingrédients, allergènes',
    all: 'Tout',
    featured: 'À découvrir',
    allergens: 'Allergènes',
    noResults: 'Aucun plat trouvé.',
    changeVenue: 'Changer de lieu',
    admin: 'Admin',
    adminArea: 'Espace admin',
    chooseAdminVenue: 'Choisir le lieu à gérer',
    manageMenu: 'Gérer le menu',
    manageMenuCucina: 'Gérer le menu restaurant',
    manageMenuAperitivi: "Gérer le menu apéritif",
    adminSeparateLink: 'Cet espace est séparé du menu client. Accès protégé par email et mot de passe.',
    pin: 'PIN administrateur',
    enterPin: 'Saisir le PIN admin',
    unlock: 'Entrer',
    wrongPin: 'PIN incorrect.',
    close: 'Fermer',
    active: 'Actif',
    inactive: 'Inactif',
    price: 'Prix',
    category: 'Catégorie',
    save: 'Enregistrer',
    addDish: 'Nouveau plat',
    addCategory: 'Nouvelle catégorie',
    dishes: 'Plats',
    categories: 'Catégories',
    qrLinks: 'QR et liens',
    photo: 'Photo',
    description: 'Description',
    name: 'Nom',
    supabaseLocal: 'Données locales de démo actives. Supabase non configuré.',
    supabaseReady: 'Supabase actif. Les données sont enregistrées en ligne.',
    openMenu: 'Ouvrir le menu',
    email: 'Email',
    password: 'Mot de passe',
    loginTitle: 'Connexion admin',
    logout: 'Déconnexion',
    serviceSelectTitle: 'Choisir un service',
    serviceCucina: 'Restaurant / Cuisine',
    serviceAperitivo: 'Apéritif',
    aperitivoComingSoon: 'La section apéritif est en cours de mise à jour. Revenez bientôt.',
    serviceTypeLabel: 'Type de service'
  },
  de: {
    chooseExperience: 'Waehle dein Erlebnis',
    chooseExperienceLine1: 'Wähle',
    chooseExperienceLine2: 'Dein',
    chooseExperienceLine3: 'Erlebnis',
    diningEyebrow: 'Zum Dinner',
    diningTitle: 'Küche',
    diningDescription: 'Zeitgenössische italienische Aromen, ausgewählte Weine und eine Gastlichkeit, die zum Verweilen einlädt.',
    aperitivoEyebrow: 'Zum Aperitif',
    aperitivoTitle: 'Cocktailbar',
    aperitivoDescription: 'Elegante Drinks, feine Kleinigkeiten und eine lebendige Atmosphäre für den perfekten Aperitif.',
    chooseVenue: 'Lokal wählen',
    menu: 'Speisekarte',
    search: 'Gerichte, Zutaten, Allergene suchen',
    all: 'Alles',
    featured: 'Empfohlen',
    allergens: 'Allergene',
    noResults: 'Keine Gerichte gefunden.',
    changeVenue: 'Lokal wechseln',
    admin: 'Admin',
    adminArea: 'Admin-Bereich',
    chooseAdminVenue: 'Lokal zur Verwaltung wählen',
    manageMenu: 'Menü verwalten',
    manageMenuCucina: 'Restaurant-Menü verwalten',
    manageMenuAperitivi: 'Aperitif-Menü verwalten',
    adminSeparateLink: 'Dieser Bereich ist vom Gästemenü getrennt. Zugang geschützt mit E-Mail und Passwort.',
    pin: 'Admin-PIN',
    enterPin: 'Admin-PIN eingeben',
    unlock: 'Öffnen',
    wrongPin: 'Falsche PIN.',
    close: 'Schließen',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    price: 'Preis',
    category: 'Kategorie',
    save: 'Speichern',
    addDish: 'Neues Gericht',
    addCategory: 'Neue Kategorie',
    dishes: 'Gerichte',
    categories: 'Kategorien',
    qrLinks: 'QR und Links',
    photo: 'Foto',
    description: 'Beschreibung',
    name: 'Name',
    supabaseLocal: 'Lokale Demodaten aktiv. Supabase ist nicht konfiguriert.',
    supabaseReady: 'Supabase aktiv. Die Daten werden online gespeichert.',
    openMenu: 'Menü öffnen',
    email: 'E-Mail',
    password: 'Passwort',
    loginTitle: 'Admin-Anmeldung',
    logout: 'Abmelden',
    serviceSelectTitle: 'Service wählen',
    serviceCucina: 'Restaurant / Küche',
    serviceAperitivo: 'Aperitif',
    aperitivoComingSoon: 'Der Aperitif-Bereich wird aktualisiert. Bald wieder verfügbar.',
    serviceTypeLabel: 'Servicetyp'
  },
  es: {
    chooseExperience: 'Elige tu experiencia',
    chooseExperienceLine1: 'Elige',
    chooseExperienceLine2: 'Tu',
    chooseExperienceLine3: 'Experiencia',
    diningEyebrow: 'Para cenar',
    diningTitle: 'Cocina',
    diningDescription: 'Sabores italianos contemporáneos, vinos seleccionados y una acogida pensada para quedarse.',
    aperitivoEyebrow: 'Para el aperitivo',
    aperitivoTitle: 'Cocktail Bar',
    aperitivoDescription: 'Coctelería elegante, bocados refinados y una atmósfera viva pensada para el ritual del aperitivo.',
    chooseVenue: 'Elige local',
    menu: 'Menú',
    search: 'Buscar platos, ingredientes, alérgenos',
    all: 'Todo',
    featured: 'Destacados',
    allergens: 'Alérgenos',
    noResults: 'No se encontraron platos.',
    changeVenue: 'Cambiar local',
    admin: 'Admin',
    adminArea: 'Área admin',
    chooseAdminVenue: 'Elige el local a gestionar',
    manageMenu: 'Gestionar menú',
    manageMenuCucina: 'Gestionar menú restaurante',
    manageMenuAperitivi: 'Gestionar menú aperitivo',
    adminSeparateLink: 'Esta área está separada del menú de clientes. Acceso protegido con email y contraseña.',
    pin: 'PIN administrador',
    enterPin: 'Introduce PIN admin',
    unlock: 'Entrar',
    wrongPin: 'PIN incorrecto.',
    close: 'Cerrar',
    active: 'Activo',
    inactive: 'Inactivo',
    price: 'Precio',
    category: 'Categoría',
    save: 'Guardar',
    addDish: 'Nuevo plato',
    addCategory: 'Nueva categoría',
    dishes: 'Platos',
    categories: 'Categorías',
    qrLinks: 'QR y enlaces',
    photo: 'Foto',
    description: 'Descripción',
    name: 'Nombre',
    supabaseLocal: 'Datos demo locales activos. Supabase no configurado.',
    supabaseReady: 'Supabase activo. Los datos se guardan en línea.',
    openMenu: 'Abrir menú',
    email: 'Email',
    password: 'Contraseña',
    loginTitle: 'Acceso admin',
    logout: 'Cerrar sesión',
    serviceSelectTitle: 'Elegir servicio',
    serviceCucina: 'Restaurante / Cocina',
    serviceAperitivo: 'Aperitivo',
    aperitivoComingSoon: 'La sección de aperitivo está en actualización. Vuelve pronto.',
    serviceTypeLabel: 'Tipo de servicio'
  },
  ru: {
    chooseExperience: 'Выберите свой формат',
    chooseExperienceLine1: 'Выберите',
    chooseExperienceLine2: 'Свой',
    chooseExperienceLine3: 'Формат',
    diningEyebrow: 'Для ужина',
    diningTitle: 'Кухня',
    diningDescription: 'Современные итальянские вкусы, отборные вина и атмосфера, в которой хочется остаться дольше.',
    aperitivoEyebrow: 'Для аперитива',
    aperitivoTitle: 'Коктейль-бар',
    aperitivoDescription: 'Элегантная миксология, изысканные закуски и живая атмосфера для идеального аперитива.',
    chooseVenue: 'Выберите заведение',
    menu: 'Меню',
    search: 'Поиск блюд, ингредиентов и аллергенов',
    all: 'Все',
    featured: 'Рекомендуем',
    allergens: 'Аллергены',
    noResults: 'Блюда не найдены.',
    changeVenue: 'Сменить заведение',
    admin: 'Админ',
    adminArea: 'Зона админа',
    chooseAdminVenue: 'Выберите заведение для управления',
    manageMenu: 'Управлять меню',
    manageMenuCucina: 'Управлять меню ресторана',
    manageMenuAperitivi: 'Управлять меню аперитива',
    adminSeparateLink: 'Эта зона отделена от клиентского меню. Доступ защищён email и паролем.',
    pin: 'PIN администратора',
    enterPin: 'Введите PIN администратора',
    unlock: 'Войти',
    wrongPin: 'Неверный PIN.',
    close: 'Закрыть',
    active: 'Активно',
    inactive: 'Неактивно',
    price: 'Цена',
    category: 'Категория',
    save: 'Сохранить',
    addDish: 'Новое блюдо',
    addCategory: 'Новая категория',
    dishes: 'Блюда',
    categories: 'Категории',
    qrLinks: 'QR и ссылки',
    photo: 'Фото',
    description: 'Описание',
    name: 'Название',
    supabaseLocal: 'Активны локальные демоданные. Supabase не настроен.',
    supabaseReady: 'Supabase активен. Данные сохраняются онлайн.',
    openMenu: 'Открыть меню',
    email: 'Email',
    password: 'Пароль',
    loginTitle: 'Вход для администратора',
    logout: 'Выйти',
    serviceSelectTitle: 'Выберите сервис',
    serviceCucina: 'Ресторан / Кухня',
    serviceAperitivo: 'Аперитив',
    aperitivoComingSoon: 'Раздел аперитива обновляется. Скоро будет доступен.',
    serviceTypeLabel: 'Тип сервиса'
  }
};

export const allergenLabels: Record<string, Record<LanguageCode, string>> = {
  gluten: { it: 'Glutine', en: 'Gluten', fr: 'Gluten', de: 'Gluten', es: 'Gluten', ru: 'Глютен' },
  milk: { it: 'Latte', en: 'Milk', fr: 'Lait', de: 'Milch', es: 'Leche', ru: 'Молоко' },
  eggs: { it: 'Uova', en: 'Eggs', fr: 'Oeufs', de: 'Eier', es: 'Huevos', ru: 'Яйца' },
  nuts: { it: 'Frutta a guscio', en: 'Tree nuts', fr: 'Fruits à coque', de: 'Schalenfrüchte', es: 'Frutos secos', ru: 'Орехи' },
  celery: { it: 'Sedano', en: 'Celery', fr: 'Céleri', de: 'Sellerie', es: 'Apio', ru: 'Сельдерей' },
  sulfites: { it: 'Solfiti', en: 'Sulfites', fr: 'Sulfites', de: 'Sulfite', es: 'Sulfitos', ru: 'Сульфиты' },
  molluscs: { it: 'Molluschi', en: 'Molluscs', fr: 'Mollusques', de: 'Weichtiere', es: 'Moluscos', ru: 'Моллюски' },
  fish: { it: 'Pesce', en: 'Fish', fr: 'Poisson', de: 'Fisch', es: 'Pescado', ru: 'Рыба' },
  sesame: { it: 'Sesamo', en: 'Sesame', fr: 'Sésame', de: 'Sesam', es: 'Sésamo', ru: 'Кунжут' },
  soy: { it: 'Soia', en: 'Soy', fr: 'Soja', de: 'Soja', es: 'Soja', ru: 'Соя' }
};

export const txt = (lang: LanguageCode, key: string) => uiText[lang][key] ?? uiText.it[key] ?? key;

export const allergenText = (allergen: string, lang: LanguageCode) =>
  allergenLabels[allergen]?.[lang] ?? allergen;
