-- Modello normalizzato: la scorta è ricostruibile dalla somma dei movimenti.
create table if not exists public.medication_profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, pin_hash text, biometric_enabled boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.medications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, dose_quantity numeric(10,2) not null check (dose_quantity > 0), daily_intakes smallint not null check (daily_intakes > 0), start_date date not null, end_date date, instructions text, low_stock_threshold numeric(10,2) not null default 5, package_photo_path text, status text not null default 'active' check (status in ('active','suspended')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.dose_schedules (id uuid primary key default gen_random_uuid(), medication_id uuid not null references public.medications(id) on delete cascade, scheduled_time time not null, reminder_after_minutes smallint not null default 20, unique (medication_id, scheduled_time));
create table if not exists public.intakes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, medication_id uuid not null references public.medications(id), schedule_id uuid references public.dose_schedules(id), scheduled_at timestamptz not null, taken_at timestamptz, planned_quantity numeric(10,2) not null, status text not null check (status in ('due','taken','late','skipped','upcoming')), notes text, original_record jsonb, created_at timestamptz not null default now(), unique (user_id, schedule_id, scheduled_at));
create table if not exists public.stock_movements (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, medication_id uuid not null references public.medications(id) on delete cascade, intake_id uuid references public.intakes(id), quantity numeric(10,2) not null, movement_type text not null check (movement_type in ('package_load','intake','manual_adjustment','intake_reversal')), note text, created_at timestamptz not null default now());
create table if not exists public.medication_notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, intake_id uuid references public.intakes(id) on delete cascade, scheduled_for timestamptz not null, delivered_at timestamptz, action text, snooze_minutes smallint, created_at timestamptz not null default now());
create table if not exists public.medication_audit_log (id bigint generated always as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, entity_type text not null, entity_id text not null, action text not null, before_data jsonb, after_data jsonb, created_at timestamptz not null default now());
create or replace view public.medication_stock as select m.id medication_id, m.user_id, coalesce(sum(sm.quantity),0) remaining_quantity from public.medications m left join public.stock_movements sm on sm.medication_id=m.id group by m.id,m.user_id;
alter table public.medication_profiles enable row level security; alter table public.medications enable row level security; alter table public.dose_schedules enable row level security; alter table public.intakes enable row level security; alter table public.stock_movements enable row level security; alter table public.medication_notifications enable row level security; alter table public.medication_audit_log enable row level security;
create policy "profiles_own" on public.medication_profiles for all using (id=auth.uid()) with check (id=auth.uid());
create policy "medications_own" on public.medications for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "schedules_own" on public.dose_schedules for all using (exists(select 1 from public.medications m where m.id=medication_id and m.user_id=auth.uid())) with check (exists(select 1 from public.medications m where m.id=medication_id and m.user_id=auth.uid()));
create policy "intakes_own" on public.intakes for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "movements_own" on public.stock_movements for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "notifications_own" on public.medication_notifications for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "audit_own" on public.medication_audit_log for select using (user_id=auth.uid());
